name: docker-kicad-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_docker-kicad-ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/domi3006/docker-kicad-ci:latest
      - name: Login to docker registry
        run: echo $CR_PAT | docker login ghcr.io -u domi3006 --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Push to registry
        run: docker push ghcr.io/domi3006/docker-kicad-ci:latest
