name: docker-kicad-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_docker-kicad-ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker-kicad-ci:$(git describe --always)-$(date +%Y%m%d%H%M%S)
